/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    services: Service;
    doctors: Doctor;
    cases: Case;
    testimonials: Testimonial;
    'gallery-items': GalleryItem;
    posts: Post;
    bookings: Booking;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'gallery-items': GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ka' | 'en' | 'ru') | ('ka' | 'en' | 'ru')[];
  globals: {
    home: Home;
    settings: Setting;
    navigation: Navigation;
    theme: Theme;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
  };
  locale: 'ka' | 'en' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * URL segment, lowercase latin letters and dashes. Shared by all languages.
   */
  slug: string;
  title: string;
  subtitle?: string | null;
  heroImage?: (number | null) | Media;
  layout?:
    | (
        | {
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            width?: ('narrow' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image: number | Media;
            imagePosition?: ('right' | 'left') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            heading?: string | null;
            images: (number | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            text?: string | null;
            buttonLabel?: string | null;
            buttonHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  /**
   * Shown on the page and submitted to Google as FAQ structured data, which can win extra space in search results.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Overrides what Google and social networks show. Leave blank to auto-generate.
   */
  seo?: {
    /**
     * Browser tab and Google result headline. Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Google result snippet. Aim for 140–160 characters.
     */
    description?: string | null;
    /**
     * Comma separated. Minor ranking value, useful as an internal note.
     */
    keywords?: string | null;
    /**
     * Preview image for Facebook, WhatsApp and X. 1200×630 works best.
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  showInSitemap?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers and Google Images. Leave empty for purely decorative images.
   */
  alt?: string | null;
  caption?: string | null;
  /**
   * Photographer or source, if attribution is required.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * URL segment, lowercase latin letters and dashes. Shared by all languages.
   */
  slug: string;
  title: string;
  /**
   * Used in navigation and cards when the full title is long.
   */
  shortTitle?: string | null;
  /**
   * One or two sentences shown on cards and in search results.
   */
  excerpt: string;
  /**
   * The main article. Longer, genuinely useful copy ranks better - aim for 600+ words per language.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlights?:
    | {
        text: string;
        icon?:
          | (
              | 'check'
              | 'tooth'
              | 'shield'
              | 'clock'
              | 'sparkle'
              | 'heart'
              | 'scan'
              | 'microscope'
              | 'lab'
              | 'child'
              | 'braces'
              | 'globe'
              | 'wallet'
              | 'pin'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on the page and submitted to Google as FAQ structured data, which can win extra space in search results.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  icon?:
    | (
        | 'implant'
        | 'veneer'
        | 'whitening'
        | 'braces'
        | 'surgery'
        | 'filling'
        | 'child'
        | 'crown'
        | 'scan'
        | 'tooth'
        | 'sparkle'
        | 'lab'
        | 'microscope'
      )
    | null;
  /**
   * Starting price in GEL. Leave empty to hide pricing.
   */
  priceFrom?: number | null;
  /**
   * Upper bound in GEL.
   */
  priceTo?: number | null;
  /**
   * For example: final price is set after a free consultation.
   */
  priceNote?: string | null;
  /**
   * Typical treatment time, e.g. "1–2 visits".
   */
  duration?: string | null;
  /**
   * Overrides what Google and social networks show. Leave blank to auto-generate.
   */
  seo?: {
    /**
     * Browser tab and Google result headline. Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Google result snippet. Aim for 140–160 characters.
     */
    description?: string | null;
    /**
     * Comma separated. Minor ranking value, useful as an internal note.
     */
    keywords?: string | null;
    /**
     * Preview image for Facebook, WhatsApp and X. 1200×630 works best.
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  /**
   * Show on the home page services grid.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  relatedDoctors?: (number | Doctor)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  /**
   * URL segment, lowercase latin letters and dashes. Shared by all languages.
   */
  slug: string;
  /**
   * Written in the script of each language.
   */
  name: string;
  /**
   * For example: Orthodontist, Implantologist.
   */
  specialty: string;
  /**
   * For example: Chief Doctor. Leave empty for regular staff.
   */
  role?: string | null;
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Year they started practising. Used to show years of experience.
   */
  experienceSince?: number | null;
  languages?: ('ka' | 'en' | 'ru' | 'de' | 'tr' | 'ar')[] | null;
  credentials?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Overrides what Google and social networks show. Leave blank to auto-generate.
   */
  seo?: {
    /**
     * Browser tab and Google result headline. Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Google result snippet. Aim for 140–160 characters.
     */
    description?: string | null;
    /**
     * Comma separated. Minor ranking value, useful as an internal note.
     */
    keywords?: string | null;
    /**
     * Preview image for Facebook, WhatsApp and X. 1200×630 works best.
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Show on the home page.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: number;
  /**
   * For example: Upper jaw implants and zirconia crowns.
   */
  title: string;
  /**
   * Shoot before and after from the same angle so the slider lines up.
   */
  beforeImage: number | Media;
  afterImage: number | Media;
  /**
   * What the problem was and how it was solved.
   */
  description?: string | null;
  treatment?: (number | null) | Service;
  doctor?: (number | null) | Doctor;
  /**
   * For example: 6 months, 3 visits.
   */
  duration?: string | null;
  /**
   * Confirm the patient agreed in writing to publish these photos.
   */
  patientConsent: boolean;
  /**
   * Show on the home page.
   */
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  patientName: string;
  /**
   * The patient’s own words. Keep it verbatim where possible.
   */
  quote: string;
  /**
   * For example: Israel. Shown with a flag on the card.
   */
  country?: string | null;
  /**
   * Two-letter ISO code used to pick the flag, e.g. IL, DE, ES, GE.
   */
  countryCode?: string | null;
  /**
   * Feeds the aggregate rating shown to Google.
   */
  rating?: number | null;
  treatment?: (number | null) | Service;
  doctor?: (number | null) | Doctor;
  photo?: (number | null) | Media;
  /**
   * YouTube link, if there is a video version of this testimonial.
   */
  videoUrl?: string | null;
  source?: ('clinic' | 'instagram' | 'facebook' | 'google') | null;
  /**
   * Highlights the card, for well-known guests such as athletes or chefs.
   */
  isPublicFigure?: boolean | null;
  /**
   * Show on the home page.
   */
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items".
 */
export interface GalleryItem {
  id: number;
  title?: string | null;
  image: number | Media;
  category: 'interior' | 'equipment' | 'team' | 'kids' | 'vip';
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * URL segment, lowercase latin letters and dashes. Shared by all languages.
   */
  slug: string;
  title: string;
  excerpt: string;
  coverImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown on the page and submitted to Google as FAQ structured data, which can win extra space in search results.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Overrides what Google and social networks show. Leave blank to auto-generate.
   */
  seo?: {
    /**
     * Browser tab and Google result headline. Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Google result snippet. Aim for 140–160 characters.
     */
    description?: string | null;
    /**
     * Comma separated. Minor ranking value, useful as an internal note.
     */
    keywords?: string | null;
    /**
     * Preview image for Facebook, WhatsApp and X. 1200×630 works best.
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  publishedAt: string;
  author?: (number | null) | Doctor;
  relatedServices?: (number | Service)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  message?: string | null;
  service?: (number | null) | Service;
  preferredDate?: string | null;
  /**
   * Language the visitor was browsing in.
   */
  locale?: string | null;
  /**
   * Page the request came from.
   */
  sourcePath?: string | null;
  status?: ('new' | 'contacted' | 'booked' | 'closed') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Editors manage content. Administrators can also manage users.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'cases';
        value: number | Case;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'gallery-items';
        value: number | GalleryItem;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  subtitle?: T;
  heroImage?: T;
  layout?:
    | T
    | {
        richText?:
          | T
          | {
              heading?: T;
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              heading?: T;
              content?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              text?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
        noindex?: T;
      };
  showInSitemap?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  shortTitle?: T;
  excerpt?: T;
  body?: T;
  highlights?:
    | T
    | {
        text?: T;
        icon?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  image?: T;
  gallery?: T;
  icon?: T;
  priceFrom?: T;
  priceTo?: T;
  priceNote?: T;
  duration?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
        noindex?: T;
      };
  featured?: T;
  order?: T;
  relatedDoctors?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  specialty?: T;
  role?: T;
  photo?: T;
  bio?: T;
  experienceSince?: T;
  languages?: T;
  credentials?:
    | T
    | {
        text?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
        noindex?: T;
      };
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  title?: T;
  beforeImage?: T;
  afterImage?: T;
  description?: T;
  treatment?: T;
  doctor?: T;
  duration?: T;
  patientConsent?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  patientName?: T;
  quote?: T;
  country?: T;
  countryCode?: T;
  rating?: T;
  treatment?: T;
  doctor?: T;
  photo?: T;
  videoUrl?: T;
  source?: T;
  isPublicFigure?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  category?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  excerpt?: T;
  coverImage?: T;
  body?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
        noindex?: T;
      };
  publishedAt?: T;
  author?: T;
  relatedServices?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  message?: T;
  service?: T;
  preferredDate?: T;
  locale?: T;
  sourcePath?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroEyebrow?: string | null;
  heroTitle: string;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Optional background video. Keep it under 5 seconds and muted.
   */
  heroVideoUrl?: string | null;
  heroBullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  primaryCtaLabel?: string | null;
  primaryCtaHref?: string | null;
  /**
   * Drag to reorder. Uncheck "enabled" to hide a section without deleting its content.
   */
  sections?:
    | {
        blockType:
          | 'stats'
          | 'services'
          | 'whyUs'
          | 'cases'
          | 'doctors'
          | 'testimonials'
          | 'kids'
          | 'tourism'
          | 'gallery'
          | 'contact';
        enabled?: boolean | null;
        heading?: string | null;
        subheading?: string | null;
        id?: string | null;
      }[]
    | null;
  advantages?:
    | {
        title: string;
        description?: string | null;
        icon?:
          | (
              | 'sparkle'
              | 'shield'
              | 'clock'
              | 'globe'
              | 'heart'
              | 'microscope'
              | 'wallet'
              | 'pin'
              | 'lab'
              | 'child'
              | 'check'
              | 'tooth'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Overrides what Google and social networks show. Leave blank to auto-generate.
   */
  seo?: {
    /**
     * Browser tab and Google result headline. Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Google result snippet. Aim for 140–160 characters.
     */
    description?: string | null;
    /**
     * Comma separated. Minor ranking value, useful as an internal note.
     */
    keywords?: string | null;
    /**
     * Preview image for Facebook, WhatsApp and X. 1200×630 works best.
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  clinicName?: string | null;
  tagline?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  /**
   * Fallback preview image for pages without their own.
   */
  defaultShareImage?: (number | null) | Media;
  phonePrimary?: string | null;
  phoneSecondary?: string | null;
  /**
   * Digits only, including country code.
   */
  whatsapp?: string | null;
  email?: string | null;
  addressLine?: string | null;
  city?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  /**
   * Google Maps link used by the "Get directions" button.
   */
  mapUrl?: string | null;
  /**
   * Uncheck to define different hours per weekday.
   */
  openEveryDay?: boolean | null;
  opensAt?: string | null;
  closesAt?: string | null;
  /**
   * For example: emergency care available outside these hours.
   */
  hoursNote?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  tiktok?: string | null;
  /**
   * The animated counters shown on the home page.
   */
  stats?:
    | {
        /**
         * e.g. 13
         */
        value: string;
        /**
         * e.g. + or %
         */
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  insurancePartners?:
    | {
        name: string;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  awards?:
    | {
        title: string;
        year?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Measurement ID, e.g. G-XXXXXXXXXX.
   */
  googleAnalyticsId?: string | null;
  /**
   * Verification token from Google Search Console.
   */
  googleSiteVerification?: string | null;
  metaPixelId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?:
    | {
        label: string;
        /**
         * Path without the language prefix, e.g. /services or /contact.
         */
        href: string;
        children?:
          | {
              label: string;
              /**
               * Path without the language prefix, e.g. /services or /contact.
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * Path without the language prefix, e.g. /services or /contact.
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * Headings and primary buttons.
   */
  primary?: string | null;
  /**
   * Highlights, badges, hover states.
   */
  accent?: string | null;
  /**
   * Logo accent and dividers.
   */
  gold?: string | null;
  /**
   * Warm page background.
   */
  background?: string | null;
  /**
   * Cards and panels.
   */
  surface?: string | null;
  /**
   * Body copy.
   */
  text?: string | null;
  headingScale?: ('compact' | 'balanced' | 'bold') | null;
  radius?: ('sharp' | 'soft' | 'pill') | null;
  /**
   * Visitors who set "reduce motion" in their device always get the reduced version regardless of this setting.
   */
  motionLevel?: ('full' | 'subtle' | 'off') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  heroVideoUrl?: T;
  heroBullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  sections?:
    | T
    | {
        blockType?: T;
        enabled?: T;
        heading?: T;
        subheading?: T;
        id?: T;
      };
  advantages?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
        noindex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  clinicName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  defaultShareImage?: T;
  phonePrimary?: T;
  phoneSecondary?: T;
  whatsapp?: T;
  email?: T;
  addressLine?: T;
  city?: T;
  latitude?: T;
  longitude?: T;
  mapUrl?: T;
  openEveryDay?: T;
  opensAt?: T;
  closesAt?: T;
  hoursNote?: T;
  facebook?: T;
  instagram?: T;
  youtube?: T;
  tiktok?: T;
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  insurancePartners?:
    | T
    | {
        name?: T;
        logo?: T;
        id?: T;
      };
  awards?:
    | T
    | {
        title?: T;
        year?: T;
        image?: T;
        id?: T;
      };
  googleAnalyticsId?: T;
  googleSiteVerification?: T;
  metaPixelId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  primary?: T;
  accent?: T;
  gold?: T;
  background?: T;
  surface?: T;
  text?: T;
  headingScale?: T;
  radius?: T;
  motionLevel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}